### ISSUE TITLE
Feature request: public vs private pastes  & nameable flems

### ISSUE THREAD

**Issue by foucist** [porsager/flems#33]
Just a thought, but what if flems were nameable and public by default, so they showed up on a list of flems from most recent to oldest?

Could be a good way to browse examples and ideas and experiments.  The list could have filters for the libraries used too.

I guess it could be helpful to show sizes of the non-library files included.

**Comment by pygy** [comment]
This would seriously beef up the server requirements. Currently a static host that serves the Flems file is AFAIK sufficient (since all the state is in the hash).

Implementing your suggestion would require sending the state to the sever every so often, mandating a DB of sorts, etc... In other words $$$, or more probably Danish Kroner.

**Comment by porsager** [comment]
I actually have this right around the corner, but I've been thinking that for the past two months now so don't hold your breath just yet :P

**Comment by porsager** [comment]
By the way.. You can name your flemses currently in the sidebar, but of course, that only applies to the document title.
