### ISSUE TITLE
some way to clear the console without reloading

### ISSUE THREAD

**Issue by fuzetsu** [porsager/flems#54]
It would be nice to have some way to clear the console without having to reload.

`Ctlr+L` would be nice (while focused on the console's input line).

Also, typing `console.clear()` clears the console in devtools, but not on the flem.

PS: Many have said it, but I'll say it again, flems is awesome 👍

**Comment by porsager** [comment]
That's a very good idea..

I'm thinking about the overall workings of shortcuts currently, and there is a lot to consider when we're in the context of the browser. `ctrl+l` would not do since that's what's used to set focus in the address bar allowing super fast copying to share (`ctrl+l` then `ctrl+v`) ;)
I made a similar mistake by creating tab shortcuts using `ctrl+1,2,3...`, but that's annoying for people who use that to select tabs in the browser :P (have to remove it again).
So, keyboard shortcuts needs some more thought.

I'll certainly add console.clear(), but also UI buttons to do that same.

And thanks a lot for the kind words ;)

**Comment by fuzetsu** [comment]
Indeed.. I'm a heavy user of `Ctrl+L` to focus the address bar, which is why I said "while focused on the console's input line". I feel like while focused in the console a fair percentage of users would expect  `Ctrl+L` to clear it. The rest of the time `Cltr+L` would function as expected to focus the address bar.

It's always tough to choose good keybindings on web apps because of conflicts with the browser, but I feel like sometimes it's worth the tradeoff..

All that said, I would of course respect and understand the decision to not mess with standard browser hotkeys, and anyway console.clear()/UI buttons would already make me pretty happy 😄

**Comment by porsager** [comment]
Ah, sorry, I didn't read your note properly about the shortcut only working while focus is on console input. I see that's how it works in dev tools too, so I guess that would make sense.. I'll think a bit more about it ;)
